filters_dev/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings
from filters_site.models import ArticleSitemap, SkillsSitemap, FilterSitemap, StaticSitemap

sitemaps = {
    'posts': ArticleSitemap,
    'skills': SkillsSitemap,
    'filters': FilterSitemap,
    'static': StaticSitemap
}

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^ckeditor/', include('ckeditor_uploader.urls')),
    url(r'^sitemap\.xml$', 'django.contrib.sitemaps.views.sitemap', {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap'),
    url(r'^', include('filters_site.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

filters_site/urls.py
from django.conf.urls import url
from filters_site import views


urlpatterns = [
    url(r'^$', views.general, name='general'),
    url(r'^about/$', views.about, name='about'),
    url(r'^contacts/$', views.contacts, name='contacts'),
    url(r'^blog/$', views.blog, name='blog'),
    url(r'^blog/(?P<page>\d+)', views.blog, name='blog_page'),
    url(r'^skills/(?P<num>\d+)', views.skill, name='skill'),
    url(r'^slide/(?P<num>\d+)', views.slide, name='slide'),
    url(r'^filter/(?P<filter>\d+)', views.description, name='filter'),
    url(r'^construct/(?P<filter_item>\d+)', views.construction, name='construct'),
    url(r'^all-constructions/$', views.construction, {'filter_item': '_all'}, name='construct_all'),
    url(r'^blog-post/(?P<article>\d+)', views.blog_post, name='article'),
    url(r'^ajax_form/$', views.ajax_form, name='form'),
    url(r'^ajax_lang/$', views.ajax_lang, name='lang'),
]

filters_site/models.py
import random
import string
from PIL import Image
from os import remove, path
from django.core.urlresolvers import reverse
from django.db import models
from ckeditor_uploader import fields as fields_with_up
from ckeditor import fields
from django.db.models.signals import pre_delete
from django.dispatch.dispatcher import receiver
from django.contrib.sitemaps import Sitemap


def get_uniq_name(instance, filename):
    new_name = ''.join(random.sample(string.ascii_lowercase, 6))
    new_name += filename[filename.find('.'):]
    return new_name


def compress_img(path_img, size):
    img = Image.open(path_img)
    if size == (420, 230):
        img.thumbnail(size, Image.ANTIALIAS)
        bg = Image.new('RGB', size, (255, 255, 255))
        bg.paste(img, ((size[0] - img.size[0]) // 2, (size[1] - img.size[1]) // 2))

    else:
        bg = img.resize(size)
    remove(path_img)
    bg.save(path_img)


class Filter(models.Model):
    name = models.CharField(max_length=300, verbose_name='Название', help_text='Название фильтра')
    name_en = models.CharField(max_length=300, verbose_name='Название для Eng версии', help_text='Название фильтра для'
                                                                                                 ' Eng версии')
    photo = models.ImageField(upload_to=get_uniq_name, verbose_name='Фотография')
    description = fields.RichTextField(config_name='default', verbose_name='Описание', default='')
    description_en = fields.RichTextField(config_name='default', verbose_name='Описание для Eng версии',
                                                   default='')

    class Meta:
        verbose_name = 'Фильтры и Информация'
        verbose_name_plural = 'Фильтры и Информация'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('filter', kwargs={'filter': self.id})


class Feature(models.Model):
    key = models.CharField(max_length=300, verbose_name='Характеристика')
    key_en = models.CharField(max_length=300, verbose_name='Характеристика для Eng версии')
    value = models.CharField(max_length=300, verbose_name='Значение')
    value_en = models.CharField(max_length=300, verbose_name='Значение для Eng версии')
    filter_link = models.ForeignKey(Filter, verbose_name='Фильтр', help_text='Выберете фильтр')

    class Meta:
        verbose_name = 'Пункт характеристик'
        verbose_name_plural = 'Характеристики'

    def __str__(self):
        return ''


class Construction(models.Model):
    name = models.CharField(max_length=300, verbose_name='Название', help_text='Названия кострукции')
    name_en = models.CharField(max_length=300, verbose_name='Название для Eng версии', help_text='Названия кострукции для Eng версии')
    description = models.TextField(max_length=1000, verbose_name='Описание')
    description_en = models.TextField(max_length=1000, verbose_name='Описание для Eng версии')
    filter_link = models.ForeignKey(Filter, verbose_name='Фильтр', help_text='Выберете фильтр', blank=True, null=True)

    class Meta:
        verbose_name = 'Конструкцию'
        verbose_name_plural = 'Конструкции'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('construct_all')


class Photo(models.Model):
    photo = models.ImageField(upload_to=get_uniq_name, verbose_name='Фото', help_text="Будет сжато до 420x230")
    construction_link = models.ForeignKey(Construction, verbose_name='Конструкция')

    class Meta:
        verbose_name = 'Фото'
        verbose_name_plural = 'Фотографии'

    def save(self, *args, **kwargs):
        super(Photo, self).save(*args, **kwargs)
        compress_img(self.photo.path, (420, 230))


class Post(models.Model):
    name = models.CharField(max_length=300, verbose_name='Название статьи', help_text='Название фильтра')
    name_en = models.CharField(max_length=300, verbose_name='Название статьи для Eng версии', help_text='Название фильтра для'
                                                                                                 ' Eng версии')
    photo = models.ImageField(upload_to=get_uniq_name, verbose_name='Фотография', help_text="Будет сжато до 420x230")
    description = fields_with_up.RichTextUploadingField(config_name='editor', verbose_name='Статья', default='', blank=True)
    description_en = fields_with_up.RichTextUploadingField(config_name='editor', verbose_name='Статья для Eng версии',
                                                   default='', blank=True)
    short_description = models.CharField(max_length=230, verbose_name="Краткое описание",
                                         help_text="Для страницы со статьями", default='', blank=True)
    short_description_en = models.CharField(max_length=230, verbose_name="Краткое описание для Eng версии",
                                         help_text="Для страницы со статьями", default='', blank=True)

    date = models.DateTimeField(verbose_name='Время', auto_now_add=True)

    class Meta:
        abstract = True


class Article(Post):

    class Meta:
        verbose_name = 'Статья'
        verbose_name_plural = 'Статьи блога'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('article', kwargs={'article': self.id})

    def save(self, *args, **kwargs):
        super(Article, self).save(*args, **kwargs)
        compress_img(self.photo.path, (420, 230))


class Slider(Post):

    class Meta:
        verbose_name = 'Слайд'
        verbose_name_plural = 'Блок Слайдер'

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        super(Slider, self).save(*args, **kwargs)
        compress_img(self.photo.path, (750, 300))


class Skills(Post):

    class Meta:
        verbose_name = 'Возможности'
        verbose_name_plural = 'Блок Возможности'

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        super(Skills, self).save(*args, **kwargs)
        compress_img(self.photo.path, (420, 230))

    def get_absolute_url(self):
        return reverse('skill', kwargs={'num': self.id})


class Message(models.Model):
    name = models.CharField(max_length=500, default='', verbose_name='Имя')
    company = models.CharField(max_length=500, default='', blank=True, verbose_name='Компания')
    number = models.CharField(max_length=100, default='', blank=False, verbose_name='Телефон')
    email = models.EmailField(max_length=50, default='', verbose_name='Почта')
    message = models.TextField(max_length=3000, default='', blank=True, verbose_name='Сообщение')
    file = models.FileField(upload_to=get_uniq_name, blank=True, verbose_name='Файл')
    url = models.CharField(max_length=300, default='', blank=True, verbose_name='Страница перехода')
    date = models.DateTimeField(verbose_name='Время', auto_now_add=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Сообщение'
        verbose_name_plural = 'Сообщения'


class Contacts(models.Model):
    val = models.CharField(max_length=200, blank=True, verbose_name='Значение')

    def __str__(self):
        return self.val

    class Meta:
        verbose_name = 'Контакт'
        verbose_name_plural = 'Блок Контакты'


@receiver(pre_delete, sender=Photo)
def construct_photo_delete(sender, instance, **kwargs):
    instance.photo.delete(False)


@receiver(pre_delete, sender=Article)
def article_photo_delete(sender, instance, **kwargs):
    instance.photo.delete(False)


@receiver(pre_delete, sender=Message)
def message_file_delete(sender, instance, **kwargs):
    instance.file.delete(False)

# Sitemap


class FilterSitemap(Sitemap):
    changefreq = "weekly"
    priority = 0.5

    def items(self):
        return Filter.objects.all()


class ArticleSitemap(Sitemap):
    changefreq = "weekly"
    priority = 0.5

    def items(self):
        return Article.objects.all()


class ArticleSitemap(Sitemap):
    changefreq = "weekly"
    priority = 0.5

    def items(self):
        return Article.objects.all()


class SkillsSitemap(Sitemap):
    changefreq = "weekly"
    priority = 0.5

    def items(self):
        return Skills.objects.all()


class StaticSitemap(Sitemap):
    changefreq = "weekly"
    priority = 0.5

    def items(self):
        return ['about', 'contacts', 'blog', 'construct_all']

    def location(self, item):
        return reverse(item)

filters_site/forms.py
from django import forms
from filters_site.models import Message, Slider


class MessageForm(forms.ModelForm):
    class Meta:
        model = Message
        fields = '__all__'


class SliderForm(forms.ModelForm):
    class Meta:
        model = Slider
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super(SliderForm, self).__init__(*args, **kwargs)
        self.fields['photo'].help_text = 'Изображение 750х300'

filters_site/templates/form/index.html
{% load staticfiles %}
<div id="form">
        <div id="close-form">
            <img src="{% static 'res/img/close.png' %}" alt="">
        </div>
        <div id="form-panel">
            <h2>ВАШ ЗАПРОС НА ИЗГОТОВЛЕНИЕ<br>ИЛИ КОММЕНТАРИЙ</h2>
                <div id="fields">

                    <form action="{% url 'form' %}" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        <table align="center" valign="middle">
                            <tr>
                                <td class="label-td">ИМЯ</td><!--
                                --><td class="input-td">{{ form.name }}{{ form.name.errors | striptags}}</td>
                            </tr>
                            <tr>
                                <td class="label-td">КОМПАНИЯ</td><!--
                                --><td class="input-td">{{ form.company }}{{ form.company.errors | striptags}}</td>
                            </tr>
                            <tr>
                                <td class="label-td">НОМЕР</td><!--
                                --><td class="input-td">{{ form.number }}{{ form.number.errors | striptags}}</td>
                            </tr>
                            <tr>
                                <td class="label-td">E-MAIL</td><!--
                                --><td class="input-td">{{ form.email }}{{ form.email.errors | striptags}}</td>
                            </tr>
                            <tr>
                                <td class="label-td">КОММЕНТАРИЙ</td><!--
                                --><td class="input-td last-td">
                                    {{ form.message }}{{ form.message.errors | striptags}}
                                    {{ form.file }}
                                    {{ form.url }}
                                    <div id='upload_file' class="btn"><a href="#">Загрузить файл</a></div>
                                    <div id="fileformlabel"></div>
                                    {{ form.file.errors | striptags}}
                                </td>
                            </tr>
                        </table>
                    </form>
                    <div class="btn" id="submit"><a href="#">отправить</a></div>
                </div>
        </div>
    </div>
    <script>
        $(document).ready(function () {
            $('input#id_name').attr('placeholder', 'Ваше имя');
            $('input#id_company').attr('placeholder', 'Ваша компания');
            $('input#id_number').attr('placeholder', '+3801234567');
            $('input#id_email').attr('placeholder', 'example@mail.com');
            $('input:visible').on('change', function () {
                if($.cookie('valid_data')) {
                    $.removeCookie('valid_data', {
                        path: '/'
                    });
                }
            })
            $("#close-form").on("click", function () {
                $("#for-form").empty();
                if($.cookie('item')) {
                    $.cookie('item', null);
                }
            })
            if($.cookie('valid_data')) {
                var data = JSON.parse($.cookie('valid_data'))
                $('#id_name').val(data.name);
                $('#id_number').val(data.number);
                $('#id_email').val(data.email);
            }
            $(".last-td .btn").on('click', function () {
                $('#id_file').trigger("click");
            });
            $("#id_file").on('change', function () {
                var value = $(this).val();
                if (value.lastIndexOf('\\')){
                    var i = value.lastIndexOf('\\')+1;
                }
                else{
                    var i = value.lastIndexOf('/')+1;
                }
                var filename = value.slice(i);
                var uploaded = document.getElementById("fileformlabel");
                uploaded.innerHTML = filename;
            });
            $("#submit").on('click', function () {
                var form = $('form');
                $("#id_url").val(window.location.pathname);
                if($.cookie('item')) {
                    if($("#id_message").val()) {
                         var message = "Тема: " + $.cookie('item') + '. ' + $("#id_message").val();
                    } else {
                         var message = "Тема: " + $.cookie('item');
                    }

                    $("#id_message").val(message);
                }
                var data = new FormData(form[0]);

                $.ajax({
                    type: form.attr('method'),
                    url: form.attr('action'),
                    data: data,
                    cache: false,
                    processData: false,
                    contentType: false,
                    success: function (data) {
                        if(data == "OK") {
                            var valid_data = {
                                name: $('#id_name').val(),
                                number: $('#id_number').val(),
                                email: $('#id_email').val()
                            }
                            if($.cookie('item')) {
                                $.cookie('item', null);
                            }
                            $.cookie('valid_data', JSON.stringify(valid_data),{
                                path: '/',
                                expires: 5 * 365
                            });
                            $("#form-panel").html('<h2 style="padding: 40% 20%">Спасибо за ваш запрос!<br>Наш специалист свяжется с Вами в ближайшее время.</h2>');
                            setTimeout(function () {
                                $("#form-panel").slideUp();
                                $("#for-form").empty();
                            }, 2500);

                        } else{
                            $("#for-form").empty();
                            $("#for-form").append(data);
                        }
                    }
                });
            });
        });
    </script>

filters_site/templates/form/index_eng.html
{% load staticfiles %}
<div id="form">
        <div id="close-form">
            <img src="{% static 'res/img/close.png' %}" alt="">
        </div>
        <div id="form-panel">
            <h2>YOUR REQUEST FOR PRODUCTION<br>OR A COMMENT</h2>
                <div id="fields">

                    <form action="{% url 'form' %}" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        <table align="center" valign="middle">
                            <tr>
                                <td class="label-td">NAME</td><!--
                                --><td class="input-td">{{ form.name }}{{ form.name.errors | striptags}}</td>
                            </tr>
                            <tr>
                                <td class="label-td">COMPANY</td><!--
                                --><td class="input-td">{{ form.company }}{{ form.company.errors | striptags}}</td>
                            </tr>
                            <tr>
                                <td class="label-td">PHONE NUMBER</td><!--
                                --><td class="input-td">{{ form.number }}{{ form.number.errors | striptags}}</td>
                            </tr>
                            <tr>
                                <td class="label-td">E-MAIL</td><!--
                                --><td class="input-td">{{ form.email }}{{ form.email.errors | striptags}}</td>
                            </tr>
                            <tr>
                                <td class="label-td">COMMENT</td><!--
                                --><td class="input-td last-td">
                                    {{ form.message }}{{ form.message.errors | striptags}}
                                    {{ form.file }}
                                    {{ form.url }}
                                    <div id='upload_file' class="btn"><a href="#">UPLOAD A FILE</a></div>
                                    <div id="fileformlabel"></div>
                                    {{ form.file.errors | striptags}}
                                </td>
                            </tr>
                        </table>
                    </form>
                    <div class="btn" id="submit"><a href="#">Send</a></div>
                </div>
        </div>
    </div>
    <script>
        $(document).ready(function () {
            $('input#id_name').attr('placeholder', 'Your name');
            $('input#id_company').attr('placeholder', 'Your company');
            $('input#id_number').attr('placeholder', '+3801234567');
            $('input#id_email').attr('placeholder', 'example@mail.com');
            $('input:visible').on('change', function () {
                if($.cookie('valid_data')) {
                    $.removeCookie('valid_data', {
                        path: '/'
                    });
                }
            })
            $("#close-form").on("click", function () {
                $("#for-form").empty();
                if($.cookie('item')) {
                    $.cookie('item', null);
                }
            })
            if($.cookie('valid_data')) {
                var data = JSON.parse($.cookie('valid_data'))
                $('#id_name').val(data.name);
                $('#id_number').val(data.number);
                $('#id_email').val(data.email);
            }
            $(".last-td .btn").on('click', function () {
                $('#id_file').trigger("click");
            });
            $("#id_file").on('change', function () {
                var value = $(this).val();
                if (value.lastIndexOf('\\')){
                    var i = value.lastIndexOf('\\')+1;
                }
                else{
                    var i = value.lastIndexOf('/')+1;
                }
                var filename = value.slice(i);
                var uploaded = document.getElementById("fileformlabel");
                uploaded.innerHTML = filename;
            });
            $("#submit").on('click', function () {
                var form = $('form');
                $("#id_url").val(window.location.pathname);
                if($.cookie('item')) {
                    if($("#id_message").val()) {
                         var message = "Тема: " + $.cookie('item') + '. ' + $("#id_message").val();
                    } else {
                         var message = "Тема: " + $.cookie('item');
                    }

                    $("#id_message").val(message);
                }
                var data = new FormData(form[0]);

                $.ajax({
                    type: form.attr('method'),
                    url: form.attr('action'),
                    data: data,
                    cache: false,
                    processData: false,
                    contentType: false,
                    success: function (data) {
                        if(data == "OK") {
                            var valid_data = {
                                name: $('#id_name').val(),
                                number: $('#id_number').val(),
                                email: $('#id_email').val()
                            }
                            if($.cookie('item')) {
                                $.cookie('item', null);
                            }
                            $.cookie('valid_data', JSON.stringify(valid_data),{
                                path: '/',
                                expires: 5 * 365
                            });
                            $("#form-panel").html('<h2 style="padding: 40% 20%">Thank you for your request!<br>Our expert will get in touch with you soon.</h2>');
                            setTimeout(function () {
                                $("#form-panel").slideUp();
                                $("#for-form").empty();
                            }, 2500);

                        } else{
                            $("#for-form").empty();
                            $("#for-form").append(data);
                        }
                    }
                });
            });
        });
    </script>